### PR TITLE
Added factors to check for when verifying ZigBee

### PR DESCRIPTION
**Pull request by ahboon**
Contributing testing for ZigBee into the list

### CODE REVIEW

**Comment by ahboon** [comment]
Any way I can improve the quality of my PR?

**Comment by scriptingxss** [comment]
Yes, we found discrepancies in the requirements provided. Spent some time on the proposed 4.5.1 and found different definitions of “Secured mode” “Security Mode” and their configs from various resources. 4.5.4 mentions "secure device admission" but this does not seem to be a standard term. In addition, there are different ZigBee versions (i.e. HA, 3.0, etc.) which are not covered. Perhaps one version is more vulnerable than another (unsure if this is true). Each requirement must be concise, practical and measurable with risk implications. 

It would be great if an expert in ZigBee could weigh in and contribute their thoughts. Could we reference a recent authoritative standard to back these requirements?

Reference from the PR  (a bit dated)
https://www.energy.gov/sites/prod/files/oeprod/DocumentsandMedia/Securing_ZigBee_Wireless_Networks.pdf

Additional zigbee resources reviewed with conflicting security mode definitions
https://zigbeealliance.org/wp-content/uploads/zip/zigbee-technical-presentation.zip
https://payatu.com/blog/dattatray/zigbee-security-101
https://research.kudelskisecurity.com/2017/11/01/zigbee-security-basics-part-1/

**Comment by ahboon** [comment]
> Yes, we found discrepancies in the requirements provided. Spent some time on the proposed 4.5.1 and found different definitions of “Secured mode” “Security Mode” and their configs from various resources. 4.5.4 mentions "secure device admission" but this does not seem to be a standard term. In addition, there are different ZigBee versions (i.e. HA, 3.0, etc.) which are not covered. Perhaps one version is more vulnerable than another (unsure if this is true). Each requirement must be concise, practical and measurable with risk implications.
> 
> It would be great if an expert in ZigBee could weigh in and contribute their thoughts. Could we reference a recent authoritative standard to back these requirements?
> 
> Reference from the PR (a bit dated)
> https://www.energy.gov/sites/prod/files/oeprod/DocumentsandMedia/Securing_ZigBee_Wireless_Networks.pdf
> 
> Additional zigbee resources reviewed with conflicting security mode definitions
> https://zigbeealliance.org/wp-content/uploads/zip/zigbee-technical-presentation.zip
> https://payatu.com/blog/dattatray/zigbee-security-101
> https://research.kudelskisecurity.com/2017/11/01/zigbee-security-basics-part-1/

Will improve on it.

**Comment by scriptingxss** [comment]
Awesome! Thanks for the PR btw @ahboon. This is needed. I believe @windBlaze was going to spend some time on this PR as well.

**Comment by windBlaze** [comment]
Hello! I did a quick review of the PR and the literature concerning this subject. Some thoughts below, hopefully they can help @ahboon in improving the requirements :) 

Indeed the original reference (https://www.energy.gov/sites/prod/files/oeprod/DocumentsandMedia/Securing_ZigBee_Wireless_Networks.pdf) is outdated. However, I was not able to find any recent authoritative standards concerning Zigbee security... The three most promising for me are:
- This MIT paper, which is used as a Zigbee reference by the ENISA guidelines: https://courses.csail.mit.edu/6.857/2017/project/17.pdf  [1]
- The Zigbee alliance technical presentation: https://zigbeealliance.org/wp-content/uploads/zip/zigbee-technical-presentation.zip [2]
- This 2020 study by HKCert, which also includes some recommendations on pg. 15: https://www.hkcert.org/f/blog/264453/3a1c8eed-012c-4b59-9d9e-971001d66c77-DLFE-14602.pdf [3]

I believe our requirements should address the following: 

1. There are two security architectures possible: Centralized (contains a Trust Center [TC]) and Distributed (a router replaces the TC) (ref: [2]). According to [1], the Centralized architecture is more suitable to higher security environments, because it supports install codes for joining the network (see below for example). As @scriptingxss mentionned, "Secure" or "Secured" mode is not something referenced in recent publications, thus I don't think it makes sense to add as a requirement 
2. According to [1] Zigbee 3.0 is indeed safer that Zigbee 1.2 (HA), because it supports out-of-band ways of providing the key used when joining the network to the TC, instead of having a static key. I'm not sure if it makes sense to have it as a separate requirement, or have a requirement discouraging the use of static keys, which will then automatically push developers to use 3.0 :) 
3. For security levels 2 and 3, we should include a requirement for periodic network key rotation. This lowers risk in case of compromise (the network key is known by all devices in the Zigbee network), and also answers some concerns about long-term reuse of the same key for AES encryption, as noted in [3] (pg. 15) and [1].
4. As explained in [1] in a lot of detail, a crucial part of Zigbee security is how devices join the network and learn the network key. For Centralized architectures, the safest way to do this is using an install code (ex. QR code on packaging of sensor), which is pre-installed in the sensor and transmitted out-of-band to the TC. For Distributed architectures, the safest way is to use pre-installed link keys, which should be manufacturer or application specific (i.e. not the known global link key "ZigbeeAlliance09", which I've seen used by many devices in the wild).
5. As mentioned in [3], to reduce the attack surface of the system, devices (both joining nodes and the TC / router) should only enter pairing mode with user interaction. The way I typically see this implemented is : user pushes a button on the joining sensor, and pushes a button or sends a command through a mobile app to the TC to start pairing. Pairing mode should also timeout after a short while (max. couple of minutes) if pairing is unsuccessful.
6. I've seen some IoT solutions implementing additional pairing controls, mainly by whitelisting specific sensor MAC addresses that are allowed to pair with the TC / router. In my experience, this is done on application level as an additional defense layer to prevent malicious sensors from joining. In [3] they deal with this scenario in a different way, they require (for Level 2 & 3 type applications) to: "Provide a means to validate the pairing of correct devices with user interaction (e.g. validate the S/N on the device hardware and on the admin portal", along with a means to blacklist certain devices from the network. Not sure which approach is better / more practical / more common. 

An example corresponding set of requirements could be as follows. These are really rough and drafty, just to resume the above wall-of-text and provide some more concise examples :) ) 

1. Verify a suitable Zigbee security architecture (Centralized or Distributed) is selected, depending on the security level and the application's threat model. Centralized architecture can offer higher security at the cost of flexibility. Or something along these lines :) 
2. [Optional, see reasoning above] Verify that Zigbee version 3.0 is used for new applications. If version 1.2 is used, verify that the default pre-configured global link key (ZigbeeAlliance09) is not used to join the network, except if explicitly required for compatibility reasons and if associated risks have been taken into account. 
3. Verify that the network key is periodically rotated.
4. Verify that the most secure way of joining the network available for the selected security architecture is used. For Centralized architecture, use out-of-band install codes (pre-configured unique link keys). For Distributed, use pre-configured link keys. [repeat from 2. above]: Avoid the use of the default  pre-configured global link key (ZigbeeAlliance09), except if explicitly required for compatibility reasons and if associated risks have been taken into account.
5. Verify that user interaction is required to activate pairing mode for both joining nodes and the TC / router, and that devices exit pairing mode after a pre-defined short amount of time is pairing is unsuccessful.
6. [Not sure, see notes above :) ]

**Comment by cbassem** [comment]
Closed as Zigbee was covered by PR #85.
@ahboon thank you for your contributions, we've taking these into account in PR #85 
@windBlaze thank you for the peer review!

**Pull request closed without merging**
